version: '3.1'

services:
  web:
    image: mmaines16/specifically-sports-web
    ports:
      - "4222:4200"
    networks:
      - bridge
  mongo:
    image: mongo:4.0
    restart: always
    ports:
    - "27017:27017"
    volumes:
    - ./mongodb/db:/data/db
    networks:
      - bridge
  server:
    image: ss-server:latest
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
    networks:
      - bridge
networks:
  bridge:
    
